/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/booking/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Horarios libres de un servicio en una fecha */
        get: operations["GetAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea una reserva y devuelve su folio */
        post: operations["CreateBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una reserva */
        get: operations["GetBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reservas de una fecha */
        get: operations["GetAgenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirma, completa o cancela una reserva */
        patch: operations["UpdateBookingStatus"];
        trace?: never;
    };
    "/api/catalog/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los servicios publicados con sus complementos */
        get: operations["GetServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/services/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un servicio */
        get: operations["GetServiceBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los cursos publicados */
        get: operations["GetCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un curso con temario completo */
        get: operations["GetCourseBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los productos, opcionalmente por categoría */
        get: operations["GetProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reseñas publicadas */
        get: operations["GetReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/faqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preguntas frecuentes */
        get: operations["GetFaqs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/specialists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Especialistas activos */
        get: operations["GetSpecialists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Todo lo que la página de inicio necesita en una llamada */
        get: operations["GetHomeData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Informe del estado del esquema y la seguridad */
        get: operations["DiagnosticsDatabase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aplica las migraciones pendientes */
        post: operations["RunMigrations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Borra el esquema public (destructivo) */
        post: operations["ResetDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/booking-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prueba disponibilidad, zona horaria y solapamientos */
        get: operations["BookingSmokeTests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica que la API esté viva */
        get: operations["HealthApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica la conexión a Supabase Postgres */
        get: operations["HealthDatabase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Complemento de un servicio. Suma precio y tiempo de cabina. */
        AddOnDto: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            serviceId?: number;
            name?: string | null;
            description?: string | null;
            /** Format: double */
            price?: number;
            /** Format: int32 */
            extraMinutes?: number;
        };
        /** @description Fila de la agenda del panel de administración. */
        AdminBookingDto: {
            /** Format: uuid */
            id?: string;
            code?: string | null;
            contactName?: string | null;
            contactPhone?: string | null;
            contactEmail?: string | null;
            subjectName?: string | null;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            modality?: string | null;
            status?: string | null;
            /** Format: double */
            priceTotal?: number;
            /** Format: double */
            depositAmount?: number;
            /** Format: double */
            depositPaid?: number;
            notes?: string | null;
            rfcReceiver?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /**
         * @description Respuesta de la consulta de disponibilidad.
         *
         *     Incluye la duración y el precio para que el frontend no tenga que
         *     pedirlos aparte: el precio total depende de los complementos, y el
         *     resumen lateral necesita ambos antes de que la clienta elija.
         */
        AvailabilityResponseDto: {
            /** Format: int32 */
            specialistId?: number;
            /** Format: date */
            date?: string;
            slots?: components["schemas"]["AvailabilitySlotDto"][] | null;
            /** Format: int32 */
            durationMinutes?: number;
            /** Format: double */
            basePrice?: number;
            /** Format: double */
            depositAmount?: number;
        };
        /** @description Un horario libre, ya descontado de reservas y bloqueos. */
        AvailabilitySlotDto: {
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
        };
        /** @description Detalle de una reserva concreta. */
        BookingDetailDto: {
            booking?: components["schemas"]["BookingDto"];
            /** Format: int32 */
            specialistId?: number;
            specialistName?: string | null;
            /** Format: double */
            depositPaid?: number;
            depositConfirmed?: boolean;
        };
        /** @description Reserva creada. Es lo que la clienta ve al confirmar. */
        BookingDto: {
            /** Format: uuid */
            id?: string;
            code?: string | null;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            modality?: string | null;
            status?: string | null;
            /** Format: double */
            priceTotal?: number;
            /** Format: double */
            depositAmount?: number;
            /** Format: double */
            balanceAmount?: number;
            contactName?: string | null;
            contactPhone?: string | null;
            contactEmail?: string | null;
            notes?: string | null;
            /** Format: int32 */
            serviceId?: number | null;
            /** Format: uuid */
            courseId?: string | null;
            addOnIds?: number[] | null;
            subjectName?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description Curso del catálogo con su temario completo. */
        CourseDto: {
            /** Format: uuid */
            id?: string;
            slug?: string | null;
            title?: string | null;
            tagline?: string | null;
            description?: string | null;
            tag?: string | null;
            level?: string | null;
            durationLabel?: string | null;
            /** Format: int32 */
            sessionCount?: number;
            /** Format: double */
            price?: number;
            /** Format: double */
            depositAmount?: number;
            topics?: string[] | null;
            includes?: string[] | null;
            imageUrl?: string | null;
        };
        /** @description Curso más breve, para las tarjetas de la home. */
        CourseSummaryDto: {
            /** Format: uuid */
            id?: string;
            slug?: string | null;
            title?: string | null;
            tagline?: string | null;
            tag?: string | null;
            level?: string | null;
            durationLabel?: string | null;
            /** Format: double */
            price?: number;
            /** Format: double */
            depositAmount?: number;
            imageUrl?: string | null;
        };
        /** @description Datos que envía el frontend para crear una reserva. */
        CreateBookingRequest: {
            /**
             * Format: int32
             * @description Especialista elegido; hoy solo hay Andy.
             */
            specialistId?: number;
            /**
             * Format: date-time
             * @description Inicio en UTC. El frontend lo convierte desde America/Mexico_City.
             */
            startsAt?: string;
            contactName?: string | null;
            contactPhone?: string | null;
            contactEmail?: string | null;
            /**
             * Format: int32
             * @description Servicio a agendar. Excluyente con CourseId.
             */
            serviceId?: number | null;
            /**
             * Format: uuid
             * @description Curso a agendar. Excluyente con ServiceId.
             */
            courseId?: string | null;
            /** @description Complementos que suman precio y tiempo de cabina. */
            addOnIds?: number[] | null;
            /** @description 'studio' o 'domicilio'. */
            modality?: string | null;
            notes?: string | null;
            rfcReceiver?: string | null;
            /** Format: uuid */
            studentId?: string | null;
        };
        FaqDto: {
            /** Format: uuid */
            id?: string;
            question?: string | null;
            answer?: string | null;
            category?: string | null;
            /** Format: int32 */
            sortOrder?: number;
        };
        /**
         * @description Todo lo que la home necesita, en una sola llamada.
         *
         *     Antes eran seis peticiones para pintar la página. Con una, el render es
         *     más rápido y no hay estado intermedio donde la pantalla se ve a medias.
         */
        HomeDataDto: {
            featuredCourses?: components["schemas"]["CourseSummaryDto"][] | null;
            reviews?: components["schemas"]["ReviewDto"][] | null;
            services?: components["schemas"]["ServiceSummaryDto"][] | null;
        };
        ProductDto: {
            /** Format: uuid */
            id?: string;
            slug?: string | null;
            name?: string | null;
            brand?: string | null;
            category?: string | null;
            description?: string | null;
            icon?: string | null;
            /** Format: double */
            price?: number;
            /** Format: double */
            taxRate?: number;
            imageUrl?: string | null;
            variants?: components["schemas"]["ProductVariantDto"][] | null;
        };
        ProductVariantDto: {
            /** Format: int32 */
            id?: number;
            sizeLabel?: string | null;
            sku?: string | null;
            /** Format: int32 */
            stockOnHand?: number;
            /** Format: double */
            priceOverride?: number | null;
        };
        ReviewDto: {
            /** Format: uuid */
            id?: string;
            authorName?: string | null;
            roleLabel?: string | null;
            initials?: string | null;
            /** Format: int32 */
            rating?: number;
            body?: string | null;
            /** Format: int32 */
            sortOrder?: number;
        };
        /** @description Servicio del catálogo, tal como se muestra en la web. */
        ServiceDto: {
            /** Format: int32 */
            id?: number;
            slug?: string | null;
            name?: string | null;
            tagline?: string | null;
            description?: string | null;
            badge?: string | null;
            /** Format: int32 */
            durationMinutes?: number;
            /** Format: double */
            price?: number;
            rfcRequired?: boolean;
            includes?: string[] | null;
            brands?: string[] | null;
            preparation?: string | null;
            imageUrl?: string | null;
            /** Format: int32 */
            sortOrder?: number;
        };
        ServiceSummaryDto: {
            /** Format: int32 */
            id?: number;
            slug?: string | null;
            name?: string | null;
            tagline?: string | null;
            badge?: string | null;
            /** Format: int32 */
            durationMinutes?: number;
            /** Format: double */
            price?: number;
            imageUrl?: string | null;
        };
        /**
         * @description Servicio con sus complementos anidados, que es como lo consume el
         *     asistente de reserva en un solo paso.
         */
        ServiceWithAddOnsDto: {
            service?: components["schemas"]["ServiceDto"];
            addOns?: components["schemas"]["AddOnDto"][] | null;
        };
        /** @description Resultado de intentar reservar un horario que ya se tomó. */
        SlotConflictResponse: {
            error?: string | null;
            message?: string | null;
            alternatives?: components["schemas"]["AvailabilitySlotDto"][] | null;
        };
        SpecialistDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            title?: string | null;
            bio?: string | null;
            imageUrl?: string | null;
        };
        /** @description Cambio manual del estado de una reserva. */
        UpdateBookingStatusRequest: {
            status?: string | null;
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetAvailability: {
        parameters: {
            query: {
                date: string;
                serviceId: number;
                specialistId?: number;
                addOnIds?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponseDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotConflictResponse"];
                };
            };
        };
    };
    GetBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetailDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAgenda: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBookingDto"][];
                };
            };
        };
    };
    UpdateBookingStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookingStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceWithAddOnsDto"][];
                };
            };
        };
    };
    GetServiceBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceWithAddOnsDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDto"][];
                };
            };
        };
    };
    GetCourseBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetProducts: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
        };
    };
    GetReviews: {
        parameters: {
            query: {
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"][];
                };
            };
        };
    };
    GetFaqs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaqDto"][];
                };
            };
        };
    };
    GetSpecialists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistDto"][];
                };
            };
        };
    };
    GetHomeData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeDataDto"];
                };
            };
        };
    };
    DiagnosticsDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RunMigrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResetDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingSmokeTests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
